### ISSUE TITLE
Version 4 missing

### ISSUE THREAD

**Issue by jariesdev** [ivanalayan15/JuanFi#146]
Is version 4 already a close source or opensource? Can't see any version 4 related branch. Thank you

**Comment by edmarlozada** [comment]
> Is version 4 already a close source or opensource? Can't see any version 4 related branch. Thank you
@jariesdev 
version 4 is here
https://juanfi.juansystems.com/

**Comment by jariesdev** [comment]
@edmarlozada 
Sorry, I mean the source codes. I'm using Arduino to flash the device. The site provided compiled code already.

**Comment by rexsllemel** [comment]
> @edmarlozada What I mean the source code for v4 since its claimed to be an opensource is not available on the repository. I'm using Arduino to flash the device. The site provided compiled code already so code cant be check.

Hi, source code for the latest version is not available. The developer of this project announced that the source code of the latest version will not be available because some developers copy his project and sell the program  which is against in the opensource community. I hope you'll understand. 
![image](https://github.com/ivanalayan15/JuanFi/assets/15032596/4886a626-26b6-4cd0-a794-e209dbb48375)
